### PR TITLE
Fix boolean handling in manage bootstrap user

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by bgruening** [comment]
Should be `create_api_key(` also None?

**Comment by mvdbeek** [comment]
@nuwang 
Can you also change `preset_api_key=False` on line 98? The rest looks good, thanks.

**Comment by nuwang** [comment]
Thanks for spotting that @bgruening. All fixed now.

**Comment by bgruening** [comment]
Nice! Thanks @nuwang and @mvdbeek for the review!

**Comment by nuwang** [comment]
Thanks for reviewing @mvdbeek @bgruening

**Pull request merged**
