### PR TITLE
Use molecule for testing

### PR DESCRIPTION
**Pull request by dometto**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Can you explain in more detail what you are doing here? 

Would be cool to restore testing as a github actions workflow (https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/.travis.yml).

**Comment by dometto** [comment]
Hi @bernt-matthias! This is work in progress, I'd like to use this role to automate the import of certain toolfiles and workflows, but it needs to be updated for more recent ansible versions. To do that I wanted to extend the tests, and I'm using `molecule` for that. My idea is to take the `galaxy-min` Docker image as a base, add a bootstrap api key to that, and use that to test this role.

Happy to create a GH actions workflow for the molecule tests once they are done and contribute back!

**Comment by dometto** [comment]
Oh, I just noticed that I opened this PR against the origin repo instead of against my own fork! :-D Sorry about that. I can close this and reopen when it's ready for review, if you're interested in the molecule tests.

**Comment by dometto** [comment]
@bernt-matthias sorry for accidentally having opened this PR and some others against this repo. I was doing some work refactoring this role over at https://github.com/dometto/ansible-galaxy-tools. I've now more or less finished work on it. What I've done includes:

- Making the role compatible with modern ansible versions
- Refactored the scripts used to install tools and workflows
- Simplifying the role somewhat (let the user supply their own restart galaxy handler)
- Adding molecule tests
- Adding linting

This makes the role pretty robust and usable now in my opinion. We are using it to deploy Galaxy servers in the cloud at Utrecht University. I'm wondering if you have any interest in us contributing back the changes to this repo, to ensure maintenance. (I would be willing to act as a co-maintainer for the repo if desired.)

**Comment by dometto** [comment]
Pinging @bernt-matthias

**Comment by bernt-matthias** [comment]
How can I help here?

**Comment by dometto** [comment]
This query in my [comment above](https://github.com/galaxyproject/ansible-galaxy-tools/pull/73#issuecomment-2304821380):

> I'm wondering if you have any interest in us contributing back the changes to this repo, to ensure maintenance. (I would be willing to act as a co-maintainer for the repo if desired.)

No worries if not, but thought I'd ask!

**Comment by bernt-matthias** [comment]
In general the Galaxy community is happy for any contribution. I guess that additional potential reviewers could be found here: https://matrix.to/#/#galaxyproject_admins:gitter.im (also great for discussion).

**Comment by dometto** [comment]
Sorry to revive this old thread @bernt-matthias, but thanks for your response!

> In general the Galaxy community is happy for any contribution. I guess that additional potential reviewers could be found here: https://matrix.to/#/#galaxyproject_admins:gitter.im (also great for discussion).

That's great to hear! I guess I was checking, before opening an actual PR and looking for reviewers, whether substantive changes along the lines of what I've done would be acceptable for this repo.

From the way I see it, since this repo is not compatible with newer versions of Ansible, it can't hurt that much to update it. But I would also understand if it's preferred to store things in a new repo, or some such. :)

If you think it's ok to go ahead, I can open a PR and request some reviews from people on matrix!

**Pull request closed without merging**
