### PR TITLE
Partially addresses: https://github.com/galaxyproject/ansible-galaxy-tools/issues/48

### PR DESCRIPTION
**Pull request by nuwang**
Added travis build badge
Fail tests if tools fail to install
Wait for galaxy to be ready before running tests

### CODE REVIEW

**Comment by drosofff** [comment]
since the https://github.com/ansible/ansible/issues/15915 has been closed we can also change
```
  - git clone --recursive -b stable-2.1 https://github.com/ansible/ansible
  - pip install ansible/
```
in
```
pip install ansible==2.2.0.0  # (at least)
```

**Comment by drosofff** [comment]
Maybe we should have a travis job for testing in a VM. We have this in GalaxyKickStartRepo https://github.com/ARTbio/GalaxyKickStart/blob/master/.travis.yml

**Comment by nuwang** [comment]
@drosofff Can you please do a supervisorctl restart galaxy manually and see if that works ok? I suspect that the root cause is the supervisor config being incorrect.

**Comment by drosofff** [comment]
@nuwang what do you mean by ` supervisor config being incorrect ` ?

**Comment by nuwang** [comment]
@drosofff Please see discussion here: https://github.com/galaxyproject/ansible-galaxy-tools/issues/48#issuecomment-351054426

**Comment by afgane** [comment]
I'll merge this this and as an incremental step and we can continue to look into the rest of the issues outlined #48 separately.

**Pull request merged**
